name: practice-workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main         # main
      - 'dev-*'      # dev-new      dev-this-is-new  
      - 'feature/**' # feature/new  feature/new/button
    types:
      - opened
    paths-ignore:
      - '.github/workflow/*'
  workflow_dispatch:
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Application
        uses: actions/checkout@v4
      - name: Installing Nodejs V18 
        uses: actions/setup-node@v4      
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Running Lint
        run: npm run lint
  Test:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Application
        uses: actions/checkout@v4
      - name: Installing Nodejs V18 
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Running Test
        run: npm run build
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Application
        uses: actions/checkout@v4
      - name: Installing Nodejs V18 
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Deploying Application
        run: echo "Deploying Application...." | echo "Deployed successfully..."
    
        
